# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build war and package with keycloak in docker image

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # disable shallow clone
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Build docker image
      run: |
        docker build -t keycloak-magic .
    
    - name: log in to docker
      run: echo ${{secrets.DOCKERHUB_PASSWORD}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
    
    - name: Get the tag for docker
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_SHA::8})
      
    - name: docker publish
      run: |
        docker tag keycloak-magic ${{secrets.DOCKERHUB_USERNAME}}/keycloak-magic:${{steps.vars.outputs.tag}}
        docker tag keycloak-magic ${{secrets.DOCKERHUB_USERNAME}}/keycloak-magic:latest
        docker push ${{secrets.DOCKERHUB_USERNAME}}/keycloak-magic:${{steps.vars.outputs.tag}}
        docker push ${{secrets.DOCKERHUB_USERNAME}}/keycloak-magic:latest
